[package]
name = "hello"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

# The rename a workers-rs application makes to move over
[dependencies]
worker = { package = "openworkers-worker", path = "../.." }
futures-channel = "0.3"

[profile.release]
opt-level = "s"
lto = true

[workspace]
